[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/xtensa-esp32s3-espidf/debug/rs-coffee"
firmware = "target/xtensa-esp32s3-espidf/debug/rs-coffee"

[net]
gateway = "ws://localhost:9011"

[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = 'a02yyuw'
binary = './chips/a02yyuw/chip.wasm'
